spring.application.name: auth-server

server:
  port: 9000
  forward-headers-strategy: framework
  servlet:
    context-path: /ya-auth


logging:
  level:
    root: INFO
    org.springframework: debug
    ru.lytvest: DEBUG
  file:
    name: ./logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# Указывает, что этот сервер должен проверять JWT-токены
# Spring Boot автоматически настроит JwtDecoder, используя issuer URI для поиска JWK Set
# Он ожидает, что JWK Set будет доступен по <issuer-uri>/oauth2/jwks
# Используйте тот же адрес, что и ваш сервер
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8000