spring.application.name: auth-server


logging:
  level:
    root: INFO # ??????? ??????????? ?? ?????????
    org.springframework: DEBUG # ??????? ??????????? ??? Spring
    com.example: DEBUG # ??????? ??????????? ??? ?????? ??????
  file:
    name: logs/app.log # ???? ? ????? ?????
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # ?????? ????? ? ?????
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # ?????? ????? ? ???????