server:
  port: 9000
  forward-headers-strategy: framework
  tomcat:
    use-relative-redirects: true


spring:
  application:
    name: greenhouse-oauth-server

  datasource:
    url: jdbc:h2:mem:oauthdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.security: trace
    org.springframework.security.oauth2: DEBUG
    ru.lytvest: DEBUG
  file:
    name: ./logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
